# Generated by Django 2.2.4 on 2019-10-17 08:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
                ('from_short', models.CharField(max_length=50)),
                ('_to', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326)),
                ('to_short', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
